### ISSUE TITLE
Dark Begining 2 set code discrepancy 

### ISSUE THREAD

**Issue by watkinsalex** [db-ygorganization-com/yugioh-card-history#1]
The set data for Dark Beginning 2 is coded 'DB'. Some cards within the dataset have their set variants coded as 'DB2' whereas others have this coded as 'DB'. I believe every instance of dark beginning 2 should be set coded 'DB2'

**Comment by gallantron** [comment]
Hi, can you give an example of this happening? When it does, can you click through to the official database (click in the printed date) and verify that the data we display does reflect what is shown on the official database?

**Comment by watkinsalex** [comment]
![SmartSelect_20221115_110916_YuGiOh! Tools](https://user-images.githubusercontent.com/65205063/202005067-0e9c7565-5788-4e7f-b3d7-b9de7f573671.jpg)
![Screenshot_20221115-110829_YuGiOh! Tools](https://user-images.githubusercontent.com/65205063/202005081-c3ce1aeb-d89a-4eb3-afdf-98adc876fdca.png)

You can see that when looking through the set list. "Dark beginning 2" set code is "DB" 
When looking up cards within db2 such as a legendary ocean. We can see the card belongs to 2 set lists. Both DB and DB2. I do not believe there is a DB set list only DB1 and DB2.

**Comment by gallantron** [comment]
That UI isn't anything we've made. I assume that's something you've made yourself? What data is it using?

**Comment by gallantron** [comment]
A Legendary Ocean [only lists DB2 set codes](https://db.ygorganization.com/data/card/5387) on its API page. I'm not sure what data you are using, but it's probably not ours.

**Comment by watkinsalex** [comment]
Yike that is embarrassing. You are right. The urls are very close. Sorry for taking your time and thank you for clarifying. I am glad I stumbled across another repository.
